### ISSUE TITLE
Crash on API 17

### ISSUE THREAD

**Issue by thomas-le-bihan** [optimizely/android-sdk#124] opened 2017-07-17 10:15 UTC
Hello,

We encounter an issue using your SDK on API 17. Here is the stacktrace : 
```java
07-17 09:52:46.815 18144-18144 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.NoClassDefFoundError: javax/annotation/Nonnull
                                                                            at java.lang.reflect.Method.getParameterAnnotations(Native Method)
                                                                            at java.lang.reflect.Constructor.getParameterAnnotations(Constructor.java:229)
                                                                            at com.fasterxml.jackson.databind.util.ClassUtil$Ctor.getParameterAnnotations(ClassUtil.java:1149)
                                                                            at com.fasterxml.jackson.databind.introspect.AnnotatedClass._constructNonDefaultConstructor(AnnotatedClass.java:925)
                                                                            at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveCreators(AnnotatedClass.java:462)
                                                                            at com.fasterxml.jackson.databind.introspect.AnnotatedClass.getConstructors(AnnotatedClass.java:324)
                                                                            at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:446)
                                                                            at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:307)
                                                                            at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:267)
                                                                            at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:159)
                                                                            at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:144)
                                                                            at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:219)
                                                                            at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:330)
                                                                            at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:314)
                                                                            at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:253)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:219)
                                                                            at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:141)
                                                                            at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
                                                                            at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
                                                                            at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                                                                            at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                                                                            at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                                                                            at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
                                                                            at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:206)
                                                                            at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:26)
                                                                            at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:681)
                                                                            at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:481)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3899)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3794)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2861)
                                                                            at com.optimizely.ab.config.parser.ProjectConfigJacksonDeserializer.deserialize(ProjectConfigJacksonDeserializer.java:56)
                                                                            at com.optimizely.ab.config.parser.ProjectConfigJacksonDeserializer.deserialize(ProjectConfigJacksonDeserializer.java:38)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
                                                                            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
                                                                            at com.optimizely.ab.config.parser.JacksonConfigParser.parseProjectConfig(JacksonConfigParser.java:39)
                                                                            at com.optimizely.ab.Optimizely.getProjectConfig(Optimizely.java:468)
                                                                            at com.optimizely.ab.Optimizely.access$000(Optimizely.java:87)
                                                                        	at com.optimizely.
```
How can we fix it ?

**Comment by elliotykim** [comment] 2017-07-17 13:04
Hi there,

This was recently reported to us, and we're looking into it now. Will let you know when there's a resolution.

-Elliot

cc @thomaszurkan-optimizely

**Comment by thomas-le-bihan** [comment] 2017-07-17 13:10
Ok thanks for the reply

**Comment by elliotykim** [comment] 2017-07-24 00:42
Hi,

We were unable to reproduce the error after extensive testing in the emulator and on real devices.

However, the following change will be released with v. 1.4.0 and will prevent the error from crashing your app on the affected devices:
https://github.com/optimizely/android-sdk/pull/126

If you have further questions, please feel free to ask. Thanks.

**Closed by elliotykim** 2017-07-24 00:42 UTC
